### ISSUE TITLE
SSL Error with last firmware v4.2

### ISSUE THREAD

**Issue by bugsounet** [matschik/freebox#37]
Hi, I can't login with lasted firmware (Freebox V6)
I use console and console.log error to see what happen
I seems to be an SSL error:
`UNABLE_TO_GET_ISSUER_CERT_LOCALLY`

Of course, i try to regenerate a new token by result is the same

@matschik: Do you have this issue too ?
without `https` proto it's works correctly (modified main code)

**Comment by matschik** [comment]
Hey !
I tested out the `login` method on my Freebox and I have no problem.

Which exact code leads you to the SSL error `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` ?

Which modification did you do on the main code ?

Can you have a look to these settings on http://mafreebox.freebox.fr ?
![Capture d’écran 2020-07-15 à 20 20 51](https://user-images.githubusercontent.com/34612598/87581254-e8408700-c6d8-11ea-9b29-10a7afcbdcfb.png)

**Comment by matschik** [comment]
Ok I didn't see you put the firmware version in the issue title.
I just restarted my Freebox and it's now up-to-date to 4.2.
I just got the same error as you: `UNABLE_TO_GET_ISSUER_CERT_LOCALLY`

I'm working on it !

**Comment by bugsounet** [comment]
bien sur ;)

ce que je ne comprend pas... cela fonctionnaitparfaitement avec le FW v4.0.x
depuis la mimse a jour vers FW v4.2.x (sur v6)

en retour console j'ai ceci:
`TypeError: Cannot destructure property `status` of 'undefined' or 'null'.`

pour avoir le nom de l'erreur:

```js
 async request(requestConfig) {
    let response;
    try {
      response = await this._getAxiosInstance().request(requestConfig);
    } catch (error) {
      console.log(error.code)
      const { status, data } = error.response;
```
 [2020-07-15 20:49:13.139] [LOG]    UNABLE_TO_GET_ISSUER_CERT_LOCALLY
on dirait que `Axios` n'envoi pas le certificat et/ou que free voudrait qu'il soit enregistré en local

Je peux vous fournir un token temporaire pour tester si besoin
On dirait que sur votre FB mini le probleme est pas d'actualité

**Comment by matschik** [comment]
Le firmware a changé quelque chose côté certificat HTTPS. Il faut que je trouve le bon moyen de configurer le client HTTPS.

**Comment by bugsounet** [comment]
par contre, attendez le nouveau firmware...
il y a un bug qui traine avec l'appli Freebox (justement avec le protocole SSL)
cela va `peut-etre` résoudre le souci
ils ont corriger ce bug avec prochain firmware (mais pas de date pour le déploiement)
pour le moment, je pense que porter avec une feature sans le protocole SSL serai preferable

**Comment by bugsounet** [comment]
> Le firmware a changé quelque chose côté certificat HTTPS. Il faut que je trouve le bon moyen de configurer le client HTTPS.
Jusque-là, j'utilisais ce qui était demandé par la doc: https://dev.freebox.fr/sdk/os/#https-access

j'ai passer l'apres midi dessus (et sur votre code) afin de chercher une solution ...
j'aurai jamais penser a un bug coté firmware :p (on dit ... `Merci ... Free!`)

**Comment by matschik** [comment]
J'ai trouvé un fix temporaire pour que la connexion HTTPS s'établisse jusqu'à que je trouve une solution plus propre.
Je publie le fix dès que possible sur NPM.

**Comment by matschik** [comment]
Fixed in version `1.3.1`
