### ISSUE TITLE
Renew token automatically

### ISSUE THREAD

**Issue by nouknouk** [matschik/freebox#5]
Hi,

first, thanks for your nice work.

I'm using this module in the scope of a tailor made home automation software ; the goal is to monitor 24h a day my freebox.
Unfortunately, at some point, the token expires and my requests (sent at regular interval) fall into 403 errors.
What would be the proper way to implement kind of "automatic token renewal", transparent for the module's consumer ?

Thanks in advance.

**Comment by matschik** [comment]
I didn't know the sessionToken can expire but it makes sense after all haha.
I will try to implement something to renew automatically this token properly asap.

Thanks a lot for using it :)

**Comment by matschik** [comment]
I just published version 1.3.0 on npm with automatic session token renewal :)
Don't change your code, the session token renewal is done with `request` method when the session has expired.
Enjoy and thank you for reporting !
