### ISSUE TITLE
HTTP 403 Forbidden

### ISSUE THREAD

**Issue by Gamepigeek** [matschik/freebox#97]
Salut :) Quand on utilise ta bibliothèque rapidement, c'est a dire en faisant un 
`setInterval(function(){ 
  main().catch(err => console.error(err));
}, 1000);;`

de temps en temps, le password ne correspond pas a ce que la Freebox attends et ca retourne donc un 403 :/
La librairie Axios n'est donc pas faites pour fonctionner de façon optimale ?

Merci du temps consacré en tout cas :)
Ta bibliothèque me sert ici  : https://www.serveurlardon.com/?routeur

**Comment by Gamepigeek** [comment]
`(node:15283) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/var/www/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/www/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/www/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:15283) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15283) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by matschik** [comment]
Hello ! Cette lib n'est pas fait pour utiliser comme ceci.
Tu ouvres une session et tu fais ce que tu veux à l'intérieur.
Si tu reçois une 403, tu dois `freebox.login()` une nouvelle fois.

```js
const freebox = new Freebox({});
await freebox.login();

setInterval(() => {
  const { data } = await freebox.request({
    method: "GET",
    url: "wifi/config",
  });
  console.log({ data });
}, 1000);

await freebox.logout();
```

**Comment by Gamepigeek** [comment]
`async function main() {
  const freebox = new Freebox({});

  await freebox.login();

  setInterval(async () => {
    const system = await freebox.request({
      method: "GET",
      url: "system",
    });

    const connection = await freebox.request({
      method: "GET",
      url: "connection",
    });

    io.emit("freebox", system.data.result.temp_cpub, system.data.result.uptime, connection.data.result.ipv4, connection.data.result.rate_down, connection.data.result.rate_up);
  }, 1000);

  await freebox.logout();
}

main().catch(err => console.error(err));`


Voila comment j'ai fais du coup :) 
Aucun erreur c'est parfait. Si tu le souhaites tu peux jeter un coup d'oeil ici https://www.serveurlardon.com/?routeur :)

Tu peux fermer l'issue ! Bonne continuation et merci pour ton travail ;)
